"""add_orders_and_is_sold

Revision ID: 0d8fae5b62a8
Revises: 347b56b1535e
Create Date: 2026-03-06 09:06:13.577067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8fae5b62a8'
down_revision: Union[str, Sequence[str], None] = '347b56b1535e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('orders_orders_buyer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('orders_orders_item_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_orders_id_pkey'))
    )
    op.create_index(op.f('orders_id_idx'), 'orders', ['id'], unique=False)
    op.add_column('item', sa.Column('is_sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'is_sold')
    op.drop_index(op.f('orders_id_idx'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
