"""Add image_path

Revision ID: 242a197b6cf6
Revises: bfc670dfbfa7
Create Date: 2026-02-26 14:53:13.091275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242a197b6cf6'
down_revision: Union[str, Sequence[str], None] = 'bfc670dfbfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image_path')
    # ### end Alembic commands ###
