"""add_feishu_open_id

Revision ID: 2a0d30961fbc
Revises: 8067690aa227
Create Date: 2026-03-17 07:19:38.192311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0d30961fbc'
down_revision: Union[str, Sequence[str], None] = '8067690aa227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feishu_open_id', sa.String(), nullable=True))
    op.create_index(op.f('users_feishu_open_id_idx'), 'users', ['feishu_open_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('users_feishu_open_id_idx'), table_name='users')
    op.drop_column('users', 'feishu_open_id')
    # ### end Alembic commands ###
