"""add_ai_chat_records

Revision ID: 347b56b1535e
Revises: bdb13406dc39
Create Date: 2026-03-06 07:08:52.885044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347b56b1535e'
down_revision: Union[str, Sequence[str], None] = 'bdb13406dc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_records', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('ai_chat_records_ai_chat_records_user_id_fkey'), 'ai_chat_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_chat_records_ai_chat_records_user_id_fkey'), 'ai_chat_records', type_='foreignkey')
    op.drop_column('ai_chat_records', 'user_id')
    # ### end Alembic commands ###
