"""add favorites many to many table

Revision ID: b3c870b92690
Revises: 242a197b6cf6
Create Date: 2026-03-05 06:14:50.707719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c870b92690'
down_revision: Union[str, Sequence[str], None] = '242a197b6cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_favorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('item_favorite_item_favorite_item_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('item_favorite_item_favorite_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'item_id', name=op.f('item_favorite_item_favorite_user_id_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_favorite')
    # ### end Alembic commands ###
