"""add_ai_chat_records

Revision ID: bdb13406dc39
Revises: b3c870b92690
Create Date: 2026-03-06 07:04:29.757912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb13406dc39'
down_revision: Union[str, Sequence[str], None] = 'b3c870b92690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_chat_records_ai_chat_records_id_pkey'))
    )
    op.create_index(op.f('ai_chat_records_id_idx'), 'ai_chat_records', ['id'], unique=False)
    op.drop_table('item_favorite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_favorite',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('item_favorite_item_favorite_item_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('item_favorite_item_favorite_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'item_id', name=op.f('item_favorite_item_favorite_user_id_pkey'))
    )
    op.drop_index(op.f('ai_chat_records_id_idx'), table_name='ai_chat_records')
    op.drop_table('ai_chat_records')
    # ### end Alembic commands ###
