"""Init_schema

Revision ID: bfc670dfbfa7
Revises: 
Create Date: 2026-02-25 17:13:26.438929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc670dfbfa7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_tags_id_pkey'))
    )
    op.create_index(op.f('tags_id_idx'), 'tags', ['id'], unique=False)
    op.create_index(op.f('tags_name_idx'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_users_id_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=False)
    op.create_index(op.f('users_id_idx'), 'users', ['id'], unique=False)
    op.create_index(op.f('users_phone_idx'), 'users', ['phone'], unique=False)
    op.create_index(op.f('users_username_idx'), 'users', ['username'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_offer', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('item_item_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('item_item_id_pkey'))
    )
    op.create_index(op.f('item_id_idx'), 'item', ['id'], unique=False)
    op.create_index(op.f('item_name_idx'), 'item', ['name'], unique=False)
    op.create_table('item_tag',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('item_tag_item_tag_item_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('item_tag_item_tag_tag_id_fkey')),
    sa.PrimaryKeyConstraint('item_id', 'tag_id', name=op.f('item_tag_item_tag_item_id_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tag')
    op.drop_index(op.f('item_name_idx'), table_name='item')
    op.drop_index(op.f('item_id_idx'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('users_username_idx'), table_name='users')
    op.drop_index(op.f('users_phone_idx'), table_name='users')
    op.drop_index(op.f('users_id_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('tags_name_idx'), table_name='tags')
    op.drop_index(op.f('tags_id_idx'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
