"""init_schema_with_image_embedding

Revision ID: c924f1debfb5
Revises: 
Create Date: 2026-04-20 02:59:03.872798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c924f1debfb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_base_knowledge_base_id_pkey'))
    )
    op.create_index(op.f('knowledge_base_id_idx'), 'knowledge_base', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_tags_id_pkey'))
    )
    op.create_index(op.f('tags_id_idx'), 'tags', ['id'], unique=False)
    op.create_index(op.f('tags_name_idx'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('feishu_open_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_users_id_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=False)
    op.create_index(op.f('users_feishu_open_id_idx'), 'users', ['feishu_open_id'], unique=True)
    op.create_index(op.f('users_id_idx'), 'users', ['id'], unique=False)
    op.create_index(op.f('users_phone_idx'), 'users', ['phone'], unique=False)
    op.create_index(op.f('users_username_idx'), 'users', ['username'], unique=False)
    op.create_table('ai_chat_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_chat_records_ai_chat_records_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_chat_records_ai_chat_records_id_pkey'))
    )
    op.create_index(op.f('ai_chat_records_id_idx'), 'ai_chat_records', ['id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_offer', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('inventory', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('image_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('item_item_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('item_item_id_pkey'))
    )
    op.create_index(op.f('item_id_idx'), 'item', ['id'], unique=False)
    op.create_index(op.f('item_name_idx'), 'item', ['name'], unique=False)
    op.create_table('item_tag',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('item_tag_item_tag_item_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('item_tag_item_tag_tag_id_fkey')),
    sa.PrimaryKeyConstraint('item_id', 'tag_id', name=op.f('item_tag_item_tag_item_id_pkey'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('orders_orders_buyer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('orders_orders_item_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_orders_id_pkey'))
    )
    op.create_index(op.f('orders_id_idx'), 'orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('orders_id_idx'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('item_tag')
    op.drop_index(op.f('item_name_idx'), table_name='item')
    op.drop_index(op.f('item_id_idx'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ai_chat_records_id_idx'), table_name='ai_chat_records')
    op.drop_table('ai_chat_records')
    op.drop_index(op.f('users_username_idx'), table_name='users')
    op.drop_index(op.f('users_phone_idx'), table_name='users')
    op.drop_index(op.f('users_id_idx'), table_name='users')
    op.drop_index(op.f('users_feishu_open_id_idx'), table_name='users')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('tags_name_idx'), table_name='tags')
    op.drop_index(op.f('tags_id_idx'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('knowledge_base_id_idx'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
